language: c
compiler:
  - gcc
#  - clang
sudo: false
addons:
  apt:
    packages:
    - tcl
    - bison
    - flex
    - gcc-multilib

env:
   - OV_ARCH_BITWIDTH=32 DB_COMMANDS=no_dbcommands
   - OV_ARCH_BITWIDTH=64 DB_COMMANDS=dbcommands
#fb_dbcommands does not compile with 32 bit on the 64 bit travis
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
install:
    - conda install --yes python="2.7" sphinx
    - pip install --user travis-sphinx
script:
   - cd ./build
   - tclsh ./acplt_build.tcl $DB_COMMANDS $OV_ARCH_BITWIDTH
   - travis-sphinx build

after_failure:
   - tail -n 40 acplt_build.log
   - travis-sphinx deploy   
