language: c
compiler:
- gcc
sudo: false
addons:
  apt:
    packages:
    - tcl
    - bison
    - flex
    - gcc-multilib
    - texinfo
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
env:
  matrix:
  - OV_ARCH_BITWIDTH=32 DB_COMMANDS=no_dbcommands
  - OV_ARCH_BITWIDTH=64 DB_COMMANDS=dbcommands
  global:
  - secure: aV2zLmzVQf8bPo+m4Xiog5DZ0x4iSunLCdEL0Dhm2CqhBA/Hgxz64UC1Y0eit3cRGOyu3QxP3LdV5Dmc+xMk+uIs+dpVc0NZwnIckN+3mrcg0nr6an7ZbZ8nbKf/sRbsviFvqCNNA1zaYaZ1Ub7ljV75MfOY1McJt4D/ymWPeCA=
  - secure: KSiHssC0QJMBpcp4RGl1rgZwEj+QFAFq443g4lpTB28hlcJfVYehA9SvaglBxn684nL6d84wwnzK7jXpwVm85mZQJpj9UcJYji5A/lGrtxow6ytnqhaTOhkbiBf3DNCrzpOVZPT7oIdFYthGTnDbn423MOBia/FOYeG5/cF7QeM=
install: 
script:
- cd ./build
- tclsh ./acplt_build.tcl $DB_COMMANDS $OV_ARCH_BITWIDTH
- cd ..
- mkdir html
- makeinfo --html --force doc/libov.texi -o html/ --no-warn
- cd ..
after_success:
- cd rte
- TAG="$(git rev-parse --short=10 HEAD)"
- if [[ ${OV_ARCH_BITWIDTH} == "32" && ${CC} == "gcc" ]]; then sh ./tools/travis_release_and_crossCompile.sh ; fi
- if [[ ${OV_ARCH_BITWIDTH} == "64" && ${CC} == "gcc" ]]; then sh ./tools/travis_release_64.sh ; fi
- cd ..
- git clone -q --depth=5 -b gh-pages https://$GH_TOKEN:x-oauth-basic@github.com/acplt/rte-www
- cp ./rte/acpltRTE-linux32.tar.gz ./rte-www/releases/`date +%F-%R`-${TAG}_acpltRTE-linux32.tar.gz
- cp ./rte/acpltRTE-linux64.tar.gz ./rte-www/releases/`date +%F-%R`-${TAG}_acpltRTE-linux64.tar.gz
- cp ./rte/acpltRTE-win32.zip ./rte-www/releases/`date +%F-%R`-${TAG}_acpltRTE-win32.zip
- cp ./rte/acpltRTE-RPi.tar.gz ./rte-www/releases/`date +%F-%R`-${TAG}_acpltRTE-RPi.tar.gz
- if [[ ${OV_ARCH_BITWIDTH} == "32" && ${CC} == "gcc" ]]; then sh ./rte/tools/travis_cleanReleaseDir.sh ; fi
- cd rte-www
- cd ./releases
- if [[ ${OV_ARCH_BITWIDTH} == "32" && ${CC} == "gcc" ]]; then sh ../../rte/tools/travis_createListPage.sh ; fi
- cd ..
- git rm -r -f ./doc/current/*
- mkdir doc
- cd doc
- mkdir current
- cd ..
- cp -r ../rte/html/* ./doc/current/
- git add -A ./doc/current/*
- git add -A ./releases/*
- git config --global user.email "rte_bot@outlook.de"
- git config --global user.name "rte-bot"
- git config --global push.default simple
- git commit -am "updated generated documentation (texinfo) on webpage and created releases by travis-ci
  [ci skip]"
- git push -f -q https://$GH_TOKEN:x-oauth-basic@github.com/acplt/rte-www
- cd .. && rm -rf rte-www
after_failure:
- cd ./rte/build
- tail -n 40 acplt_build.log
