language: c
compiler:
  - gcc
#  - clang
sudo: true
addons:
  apt:
    packages:
    - tcl
    - bison
    - flex
    - gcc-multilib

env:
   - OV_ARCH_BITWIDTH=32 DB_COMMANDS=no_dbcommands
   - OV_ARCH_BITWIDTH=64 DB_COMMANDS=dbcommands
#fb_dbcommands does not compile with 32 bit on the 64 bit travis
before_install:
  - sudo apt-get install -y texinfo

install: 
  - wget http://ftp.gnu.org/gnu/texinfo/texinfo-5.2.tar.xz
  - tar -xJvf texinfo-5.2.tar.xz
  - cd texinfo-5.2 && ./configure --prefix=/usr && make && sudo make install && cd ..

script:
   - cd ./build
   - tclsh ./acplt_build.tcl $DB_COMMANDS $OV_ARCH_BITWIDTH
   - makeinfo --html doc/libov.texi -o web/
after_success:
   -git clone -q --depth=5 -b gh-pages https://$GH_API_KEY@github.com/acplt/rte-www
   -cd rte-www
   -git rm -r -f ./doc/current/*
   -cp -r ../../doc/* ./doc/current/
   -git add -A ./doc/current
   -git config --global user.email "rte_bot@outlook.de"
   -git config --global user.name "rte-bot"
   -git config --global push.default simple
   -git commit -am "updated generated documentation on webpage by travis-ci [ci skip]"
   -git push https://$GH_API_TOKEN@github.com/rte-www
   -cd .. && rm -rf rte-www

after_failure:
   - tail -n 40 acplt_build.log

